# Database & Redis Credentials
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: backend-ns
type: Opaque
data:
  db-pass: {{ (default "" .Values.secrets.dbPass) | b64enc }}
  redis-pass: {{ (default "" .Values.secrets.redisPass) | b64enc }}
---
# TLS Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: frontend-ns
type: kubernetes.io/tls
data:
  tls.crt: {{ (default "" .Values.secrets.tlsCrt) | b64enc }}
  tls.key: {{ (default "" .Values.secrets.tlsKey) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: data-ns
type: Opaque
data:
  db-pass: {{ .Values.secrets.dbPass | b64enc }}
  redis-pass: {{ .Values.secrets.redisPass | b64enc }}