apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: {{ .Values.images.pullSecret | quote }}
      
      # 1. Init Containers updated to use the stable Headless DNS
      initContainers:
      - name: wait-for-postgres
        image: alpine
        command: ['sh', '-c', 'until nc -z {{ .Values.database.host }} {{ .Values.database.port }}; do echo waiting for postgres; sleep 2; done;']
      - name: wait-for-redis
        image: alpine
        command: ['sh', '-c', 'until nc -z {{ .Values.redis.host }} {{ .Values.redis.port }}; do echo waiting for redis; sleep 2; done;']

      # 2. Main Application Container
      containers:
      - name: backend
        image: {{ .Values.images.backend }}
        ports:
        - containerPort: 5000
        env:
        # Hostnames from values.yaml (Headless DNS)
        - name: DB_HOST
          value: {{ .Values.database.host | quote }}
        - name: DB_PORT
          value: {{ .Values.database.port | quote }}
        - name: REDIS_HOST
          value: {{ .Values.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ .Values.redis.port | quote }}
        
        # Credentials from Secrets
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-pass
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-pass
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-ns
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend