apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      # --- VAULT ANNOTATIONS START ---
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "backend-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/backend/config"
        # Use Helm string literals to escape the Vault curly braces
        vault.hashicorp.com/agent-inject-template-config: |
          {{ "{{" }}- with secret "secret/data/backend/config" -{{ "}}" }}
          export DB_PASS="{{ "{{" }} .Data.data.db_pass {{ "}}" }}"
          export REDIS_PASS="{{ "{{" }} .Data.data.redis_pass {{ "}}" }}"
          {{ "{{" }}- end -{{ "}}" }}
    spec:
      # Must match the bound_service_account_names in your Vault role
      serviceAccountName: backend-sa
      imagePullSecrets:
      - name: {{ .Values.images.pullSecret | quote }}
    
      initContainers:
      - name: wait-for-postgres
        image: alpine
        command: ['sh', '-c', 'until nc -z {{ .Values.database.host }} {{ .Values.database.port }}; do echo waiting for postgres; sleep 2; done;']
      - name: wait-for-redis
        image: alpine
        command: ['sh', '-c', 'until nc -z {{ .Values.redis.host }} {{ .Values.redis.port }}; do echo waiting for redis; sleep 2; done;']

      containers:
      - name: backend
        image: {{ .Values.images.backend }}
        # Sourcing the Vault secrets before starting the application
        command: ["/bin/sh", "-c", ". /vault/secrets/config && python app.py"]
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: {{ .Values.database.host | quote }}
        - name: DB_PORT
          value: {{ .Values.database.port | quote }}
        - name: REDIS_HOST
          value: {{ .Values.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ .Values.redis.port | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-ns
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend