# 1. The Deployment (The Pods)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: {{ .Values.images.pullSecret }}
      containers:
      - name: frontend
        image: {{ .Values.images.frontend }}
        ports:
        - containerPort: 80
---
# 2. The Service (The Internal Load Balancer) - MISSING IN YOUR SETUP
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-ns
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend # This MUST match the labels in the Deployment above
---
# 3. The Backend Connector
apiVersion: v1
kind: Service
metadata:
  name: backend-service-external
  namespace: frontend-ns
spec:
  type: ExternalName
  externalName: backend-service.backend-ns.svc.cluster.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: frontend-ns
  annotations:
    # REMOVE the rewrite-target annotation entirely
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service-external
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80